#pragma once
#include <cstdint>

namespace FAWorld
{
    enum class ItemEquipType
    {
        none,
        oneHanded,
        twoHanded,
        chest,
        head,
        ring,
        amulet,
        unequipable,
        belt,
        invalid,
    };

    enum class ItemType
    {
        misc = 0,
        sword,
        axe,
        bow,
        mace,
        shield,
        lightArmor,
        helm,
        mediumArmor,
        heavyArmor,
        staff,
        gold,
        ring,
        amulet,
        none = -1,
    };

    enum class ItemClass
    {
        none = 0,
        weapon,
        armor,
        jewelryAndConsumable,
        gold,
        quest,
    };

    // TODO: synchronize names with:
    // https://github.com/sanctuary/notes/blob/72a0772e0d187d29117c4ddd6e6265cafc774a50/enums.h#L128
    enum class ItemEffectType
    {
        IncPercentChanceToHit,
        DecPercentChanceToHit,
        IncPercentDamageDone,
        DecPercentDamageDone,
        IncPercentDamageDoneChanceToHit,
        DecPercentDamageDoneChanceToHit,
        IncPercentArmourClass,
        DecPercentArmourClass,
        IncPercentResistFire,
        IncPercentResistLightning,
        IncPercentResistMagic,
        IncPercentResistAll,
        Unknown6,
        Unknown7,
        ModSpellLevel,
        IncCharges,
        IncFireDamage,
        IncLightningDamage,
        Unknown8,
        IncStrength,
        DecStrength,
        IncMagic,
        DecMagic,
        IncDexterity,
        DecDexterity,
        IncVitality,
        DecVitality,
        IncAllBasicStats,
        DecAllBasicStats,
        IncDamageTaken,
        DecDamageTaken,
        IncHP,
        DecHP,
        IncMana,
        DecMana,
        IncPercentDurability,
        DecPercentDurability,
        Indestructible,
        IncLightRadius,
        DecLightRadius,
        Unknown0,
        MultipleArrows,
        IncPercentFireArrowDamage,
        IncPercentLightningArrowDamage,
        UniquePicture,
        Thorns,
        AllMana,
        PlayerNoHeal,
        Unknown1,
        Unknown2,
        Unknown3,
        Unknown4,
        HalfTrapDamage,
        Knockback,
        MonsterNoHeal,
        PercentManaSteal,
        PercentLifeSteal,
        ArmourPenetration,
        AttackSpeed0,
        HitRecovery,
        FastBlock,
        IncDamageDone,
        RandomArrowSpeed,
        UnusualDamage,
        AlteredDurability,
        NoStrengthRequirment,
        Spell,
        AttackSpeed1,
        OneHanded,
        AntiDemon,
        ZeroAllResist,
        Unknown5,
        ConstantLifeDrain,
        PercentFixedLifeSteal,
        Infravision,
        SpecifiedArmourClass,
        IncHPWithArmourClass,
        IncArmourClassWithMana,
        IncFireResistWithLevel,
        DecArmourClass
    };

    enum class ItemMiscId
    {
        none = 0,
        potionOfFullHealing = 2,
        potionOfHealing = 3,
        potionOfMana = 6,
        potionOfFullMana = 7,
        elixirOfStrength = 10,
        elixirOfMagic = 11,
        elixirOfDexterity = 12,
        elixirOfVitality = 13,
        potionOfRejuvenation = 18,
        potionOfFullRejuvenation = 19,
        scroll = 21,
        scrollWithTarget = 22,
        staff = 23,
        book = 24,
        ring = 25,
        amulet = 26,
        unique = 27,
        mapOfTheStars = 42,
        ear = 43,
        spectralElixir = 44,
        invalid = -1,
    };

    enum class ItemQuality
    {
        normal = 0,
        magic,
        unique
    };

    enum class ItemId
    {
        gold = 0,
        shortSword,
        buckler,
        club,
        shortBow,
        shortStaffOfChargedBolt,
        cleaver,
        theUndeadCrown,
        empyreanBand,
        magicRock,
        opticAmulet,
        ringOfTruth,
        tavernSign,
        harlequinCrest,
        veilOfSteel,
        goldenElixir,
        anvilOfFury,
        blackMushroom,
        brain,
        fungalTome,
        spectralElixir,
        bloodStone,
        mapOfTheStars,
        heart,
        potionOfHealing,
        potionOfMana,
        scrollOfIdentify,
        scrollOfTownPortal,
        arkainesValor,
        potionOfFullHealing,
        potionOfFullMana,
        griswoldsEdge,
        lightforge,
        staffOfLazarus,
        scrollOfResurrect,
        baseSkullCap,
        baseHelm,
        baseFullHelm,
        baseCrown,
        baseGreatHelm,
        baseCape,
        baseRags,
        baseCloak,
        baseRobe,
        baseQuiltedArmor,
        baseLeatherArmor,
        baseHardLeatherArmor,
        baseStuddedLeatherArmor,
        baseRingMail,
        baseChainMail,
        baseScaleMail,
        baseBreastPlate,
        baseSplintMail,
        basePlateMail,
        baseFieldPlate,
        baseGothicPlate,
        baseFullPlateMail,
        baseBuckler,
        baseSmallShield,
        baseLargeShield,
        baseKiteShield,
        baseTowerShield,
        baseGothicShield,
        basePotionOfHealing,
        basePotionOfFullHealing,
        basePotionOfMana,
        basePotionOfFullMana,
        basePotionOfRejuvenation,
        basePotionOfFullRejuvenation,
        baseElixirOfStrength,
        baseElixirOfMagic,
        baseElixirOfDexterity,
        baseElixirOfVitality,
        baseScrollOfHealing,
        baseScrollOfLightning,
        baseScrollOfIdentify,
        baseScrollOfResurrect,
        baseScrollOfFireWall,
        baseScrollOfInferno,
        baseScrollOfTownPortal,
        baseScrollOfFlash,
        baseScrollOfInfravision,
        baseScrollOfPhasing,
        baseScrollOfManaShield,
        baseScrollOfFlameWave,
        baseScrollOfFireball,
        baseScrollOfStoneCurse,
        baseScrollOfChainLightning,
        baseScrollOfGuardian,
        baseNonItem,
        baseScrollOfNova,
        baseScrollOfGolem,
        baseScrollOfNone,
        baseScrollOfTeleport,
        baseScrollOfApocalypse,
        baseBookQlvl2,
        baseBookQlvl8,
        baseBookQlvl14,
        baseBookQlvl20,
        baseDagger,
        baseShortSword,
        baseFalchion,
        baseScimitar,
        baseClaymore,
        baseBlade,
        baseSabre,
        baseLongSword,
        baseBroadSword,
        baseBastardSword,
        baseTwoHandedSword,
        baseGreatSword,
        baseSmallAxe,
        baseAxe,
        baseLargeAxe,
        baseBroadAxe,
        baseBattleAxe,
        baseGreatAxe,
        baseMace,
        baseMorningStar,
        baseWarHammer,
        baseSpikedClub,
        baseClub,
        baseFlail,
        baseMaul,
        baseShortBow,
        baseHuntersBow,
        baseLongBow,
        baseCompositeBow,
        baseShortBattleBow,
        baseLongBattleBow,
        baseShortWarBow,
        baseLongWarBow,
        baseShortStaff,
        baseLongStaff,
        baseCompositeStaff,
        baseQuarterStaff,
        baseWarStaff,
        baseRingQlvl5,
        baseRingQlvl10,
        baseRingQlvl15,
        baseAmuletQlvl8,
        baseAmuletQlvl16,
        COUNT,
    };

    enum class UniqueItemId
    {
        theButchersCleaver = 0,
        theUndeadCrown,
        empyreanBand,
        opticAmulet,
        ringOfTruth,
        harlequinCrest,
        veilOfSteel,
        arkainesValor,
        griswoldsEdge,
        lightforge,
        theRiftBow,
        theNeedler,
        theCelestialBow,
        deadlyHunter,
        bowOfTheDead,
        theBlackoakBow,
        flamedart,
        fleshstinger,
        windforce,
        eaglehorn,
        gonnagalsDirk,
        theDefender,
        gryphonsClaw,
        blackRazor,
        gibbousMoon,
        iceShank,
        theExecutionersBlade,
        theBonesaw,
        shadowhawk,
        wizardspike,
        lightsabre,
        theFalconsTalon,
        inferno,
        doombringer,
        theGrizzly,
        theGrandfather,
        theMangler,
        sharpBeak,
        bloodslayer,
        theCelestialAxe,
        wickedAxe,
        stonecleaver,
        aguinarasHatchet,
        hellslayer,
        messerschmidtsReaver,
        crackrust,
        hammerOfJholm,
        civerbsCudgel,
        theCelestialStar,
        baranarsStar,
        gnarledRoot,
        theCraniumBasher,
        schaefersHammer,
        dreamflange,
        staffOfShadows,
        immolator,
        stormSpire,
        gleamsong,
        thundercall,
        theProtector,
        najsPuzzler,
        mindcry,
        rodOfOnan,
        helmOfSpirits,
        thinkingCap,
        overlordsHelm,
        foolsCrest,
        gotterdamerung,
        royalCirclet,
        tornFleshOfSouls,
        theGladiatorsBane,
        theRainbowCloak,
        leatherOfAut,
        wisdomsWrap,
        sparkingMail,
        scavengerCarapace,
        nightscape,
        najsLightPlate,
        demonspikeCoat,
        theDeflector,
        splitSkullShield,
        dragonsBreach,
        blackoakShield,
        holyDefender,
        stormshield,
        bramble,
        ringOfRegha,
        theBleeder,
        constrictingRing,
        ringOfEngagement,
        null,
    };
}
